# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e500d5cea471fc1df9bf88622a3ddcf81775fc85f138e74b2045c62b0228d39ef28807f4ff7a81e950b4ea9882b82b934114a0d6f9fcb5c7704b3f63249ae0b

test:
  secret_key_base: 9495f37addcaf7000fe28ba3e621b7d7cdccd27fdf4bc5bb586f799cf222567f641a370ee4f862650a52cbff6e579fcb1396f90045f567c93776cd05148f43e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
